name: lint

on: [workflow_call]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project for ${{ matrix.python-version }} 
        run: pip install .
      - name: Install linter dependencies
        run: pip install -r requirements/requirements-lint.txt
      - name: Run mypy on ${{ matrix.python-version }}
        run: mypy gertils
      - name: Run pylint on ${{ matrix.python-version }}
        run: pylint gertils tests

