name: Tests 

on: [workflow_call]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: pip install .
      - name: Install test dependencies
        run: pip install -r requirements/requirements-test.txt
      - name: Run unit tests on Python ${{ matrix.python-version }}
        run: pytest .

